name: Test

on:
  push:
    branches:
      - main
    tags: [ "*" ]
  pull_request:

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: rustfmt
          override: true
      - name: Cache cargo build
        working-directory: pypi_types_crate
        uses: Swatinem/rust-cache@v2
      - uses: actions-rs/cargo@v1
        working-directory: pypi_types_crate
        with:
          command: fmt
          args: --all -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          components: clippy
          override: true
      - uses: actions-rs/cargo@v1
        working-directory: pypi_types_crate
        with:
          command: clippy
          args: --tests --all-features -- -D warnings

  black:
    name: Black
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - uses: psf/black@23.1.0

  ruff:
    name: ruff
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      # TODO: Put ruff in pyproject.toml dev dependencies and use lockfile version
      # or ruff github action
      - run: pipx run ruff==0.0.265 .
